Fix homepage content typos
CofferHub/thecofferhub.dev pull request #2
Opened 2021-06-21 04:50 UTC by luanrvmood

Just small fixes on page's content typo.

2021-06-22 17:22 UTC, dheysonalves commented on src/templates/VerticalFeatures.tsx
> +      description="A proposta da comunidade no discord é github, e permitir que desenvolvedores(as), estudantes, professores(as) de universidade e amantes de tecnologia possam ter um ambiente para tr
Eae Luan, o primeiro e, sem acento.

Value de mais por ajudar a gente!

2021-06-22 17:26 UTC, dheysonalves requested changes
Eae @luanrvmood, o primeiro e, e sem acento.

Valeu demais Luan por ajudar a gente!

2021-06-23 01:22 UTC, luanrvmood commented on src/templates/VerticalFeatures.tsx
> +      description="A proposta da comunidade no discord é github, e permitir que desenvolvedores(as), estudantes, professores(as) de universidade e amantes de tecnologia possam ter um ambiente para tr
troquei as bolas. hahaha my bad!

2021-06-23 01:22 UTC, luanrvmood commented on src/templates/VerticalFeatures.tsx
> +      description="A proposta da comunidade no discord é github, e permitir que desenvolvedores(as), estudantes, professores(as) de universidade e amantes de tecnologia possam ter um ambiente para tr
@dheysonalves 1411ac9

2021-06-23 01:26 UTC, dheysonalves approved these changes

2021-06-23 01:27 UTC, merged